# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwUSUQl6YtuIDStMhY5QcQVT1K29yd1f
"""

# import required libraries
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("fivethirtyeight")

# load data
df=pd.read_csv(("/content/Grocery-Store-Sales-Time-Series-Dataset.csv"),skiprows=7)
df.columns=["date","sales"]
df.head()

df.dropna(inplace=True)

# to get number of rows and columns present
df.shape

# check first few rows of dataset
df.head()

df.dtypes

df['date']=pd.to_datetime(df['date'],format='%b-%y')

df.dtypes

df.head()

df.set_index("date",inplace=True)

df.head()

# plotting the sales trend over years
plt.figure(figsize=(15,3))
df["sales"].plot()
plt.title("Grocery Store Sales over Years")
plt.xlabel("Year")
plt.ylabel("Sales")
plt.show()

"""How to make series stationary?
Use differenting technique
"""

df.info()

df.dtypes

df.head()

df1=df.diff()
df1.dropna(inplace=True)

# plotting the sales trend over years
plt.figure(figsize=(15,3))
plt.plot(df1["sales"])
plt.title("Series after differencing")
plt.xlabel(" Month Year")
plt.show()

# import plot_acf, plot_pacf functions from statsmodels library
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf

# create a 1-row, 2-column subplot
fig, ax = plt.subplots(1, 2, figsize=(14,5))

# plot PACF on the first subplot
plot_pacf(df["sales"], ax=ax[0])
ax[0].set_title("Partial Autocorrelation (PACF)")

# plot ACF on the second subplot
plot_acf(df["sales"], ax=ax[1])
ax[1].set_title("Autocorrelation (ACF)")

plt.tight_layout()
plt.show()

# splitting the dataframe into training and tseting datasets
train_df=df[:-12]
test_df=df[-12:]

"""Buliding ARIMA model on training data

"""

# import ARIMA class from statsmodel library
from  statsmodels.tsa.arima.model import ARIMA

model_arima=ARIMA(train_df,order=(1,1,1))

# build the ARIMA model
model_fit=model_arima.fit()

# summary function will help to have closer look at statistical values
print(model_fit.summary())

# forecasting the next 12 months
n_forecast = 12

# getting predictions for the forecast period (predictions for testing data)
predict = model_fit.predict(start=len(train_df), end=len(train_df) + n_forecast - 1)

# renaming series for clarity
predict.rename("predicted",inplace=True)

predict

# creating new dataframe to store predictions
pred_df=pd.DataFrame(predict)

# renaming columns for clarity
pred_df.columns=["predicted_sales"]

# rounding off values to zero deicimal places
pred_df["predicted_sales"]=round(pred_df["predicted_sales"],0)

pred_df

actual_vs_pred = pd.concat([test_df['sales'], pred_df], axis=1)
actual_vs_pred.columns = ["actual_sales", "predicted_sales"]
actual_vs_pred["error"] = actual_vs_pred["actual_sales"] - actual_vs_pred["predicted_sales"]

actual_vs_pred.head()

plt.figure(figsize=(15,4))

plt.plot(actual_vs_pred.index, actual_vs_pred["actual_sales"], label="Actual Sales")
plt.plot(actual_vs_pred.index, actual_vs_pred["predicted_sales"], label="Predicted Sales")

plt.title("Actual vs Predicted Store Sales")
plt.xlabel("Month-Year")
plt.ylabel("Sales")

plt.legend()
plt.grid(True)
plt.show()

#  !pip install numpy==1.26.4
#  !pip install pmdarima --no-cache-dir

#  import auto-arima function from pndarima library
from pmdarima import auto_arima

# # # passing non ststionary data to auto_Arima_function
auto_arima_result=auto_arima(train_df,seasonal=True,m=12)

# # summary function will help to have closer look at statistical values
print(auto_arima_result.summary())

"""Builiding SARIMAX Model on Training Data"""

# import SARIMAX class frim ststamodels library
from statsmodels.tsa.statespace.sarimax import SARIMAX

# create instance of SARIMAX class and providing values of non-seasonal and seasonal orderv
model_sarimax=SARIMAX(train_df,order=auto_arima_result.order,seasonal_order=auto_arima_result.seasonal_order)

# buliding SARIMAX model
model_sarimax_fit=model_sarimax.fit()

# time period in months for which we are forcasting sales
n_forecast=12

# predict function will return series with predicted values for testing data
pred_values=model_sarimax_fit.predict(start=len(train_df),end=len(train_df)+n_forecast-1)

# creating columns for clarity
pred_values=pred_values.rename("predicted",inplace=True)

# creating new data frame to store predicted values for test data
pred_df=pd.DataFrame(pred_values)

#rounding off values to zero decimal places
pred_df["predicted"]=round(pred_df["predicted"],0)

pred_df

# creating new dataframe to store actual test data along with prediction by SARIMAX MODEL
actual_vs_pred_df = pd.concat([test_df, pred_df], axis=1)

# CREATING ERROR in actual and predicted values
actual_vs_pred_df["error"] = actual_vs_pred_df["sales"] - actual_vs_pred["predicted"]

# remaining columns for clarity
actual_vs_pred_df.rename(columns={"sales": "actual_sales"}, inplace=True)
actual_vs_pred_df.rename(columns={"predicted": "predicted_sales"},inplace=True)

actual_vs_pred_df

# plotting actual and predicted sales over years
plt.figure(figsize=(15,4))
actual_vs_pred_df["actual_sales"].plot()
actual_vs_pred_df["predicted_sales"].plot()
plt.title("Actual and Predicted Store Sales Over Years")
plt.xlabel("Year")
plt.ylabel("Sales")
plt.show()

"""Training SARIMAX Model on entire data

"""

# passing non stationary data to auto_arima function
auto_arima_result=auto_arima(df,seasonal=True,m=12)

print(auto_arima_result.summary())

# create instance of SARIMAX class and providing values of non seasonal order given by auto_arima_function
model_sarima=SARIMAX(df,order=auto_arima_result.order,seasonal_order=auto_arima_result.seasonal_order)

# BULIDING SARIMAX MODEL
model_fit=model_sarima.fit()

# time period in months for which we are forcasting sales
n_forecast=12

# predict function will return series with predicted values
pred_values=model_fit.predict(start=len(df),end=len(df)+n_forecast-1)

# creating columns for clarity
pred_values=pred_values.rename("predicted",inplace=True)

# creating new data frame to store predicted values
pred_df=pd.DataFrame(pred_values)

#rounding off values to zero decimal places
pred_df["predicted"]=round(pred_df["predicted"],0)

pred_df

plt.figure(figsize=(15,3))
df["sales"].plot(legend=True,label="Actual")
pred_df["predicted"].plot(legend=True,label="Predicted")
plt.title("Actual and Predicted Store Sales Over Years")
plt.xlabel("Year")
plt.ylabel("Sales")
plt.legend(["Actual","Predicted"])
plt.show()

